export const mockCandidates = [
  {
    id: 0,
    candidateName: "এ, কে, এম, আবু ইউছপ",
    candidateImage: "https://i.ibb.co/TM5nZyCK/candidate1.jpg",
    partyName: "জাতীয় সামাজতান্তিক দল-কেজিএসডি",
    marka: "তারা",
    votes: "89064",
    countedCenter: "45",
    symbolImage: "https://i.ibb.co/TM5nZyCK/star.png",
  },
  {
    id: 1,
    candidateName: "রজাউন করিম",
    candidateImage: "https://i.ibb.co/cS6BgXSR/candidate2.jpg",
    partyName: "ইনসানিয়ার বিতব বালাদেশ",
    marka: "আপেল",
    votes: "75432",
    countedCenter: "38",
    symbolImage: "https://i.ibb.co/cS6BgXSR/apple.png",
  },
  {
    id: 2,
    candidateName: "মোহাম্মদ ছাইফুর রহমান",
    candidateImage: "https://i.ibb.co/1Ggmr1Tw/candidate3.jpg",
    partyName: "বাংলাদেশ জামায়েত ইসলামী",
    marka: "দাঁড়িপাল্লা",
    votes: "68210",
    countedCenter: "32",
    symbolImage: "https://i.ibb.co/1Ggmr1Tw/scale.png",
  },
  {
    id: 3,
    candidateName: "নুরুল আমন",
    candidateImage: "https://i.ibb.co/CKNsc40b/candidate4.jpg",
    partyName: "বাংলাদেশ জাতীয়বাদী দল - বি.এন.পি",
    marka: "ধানের শীষ",
    votes: "59123",
    countedCenter: "28",
    symbolImage: "https://i.ibb.co/CKNsc40b/paddy.png",
  },
  {
    id: 4,
    candidateName: "ফেরদৌস আহমদ চৌধুরী",
    candidateImage: "https://i.ibb.co/ORnVHJng/candidate5.jpg",
    partyName: "ইনসামী আমেদান বালাদেশ",
    marka: "হাতপাখা",
    votes: "47895",
    countedCenter: "24",
    symbolImage: "https://i.ibb.co/ORnVHJng/fan.png",
  },
  {
    id: 5,
    candidateName: "শেখ জুলফিকার বুলবুল চৌধুরী",
    candidateImage: "https://i.ibb.co/nqLt6WBY/candidate6.jpg",
    partyName: "বাংলাদেশ মুসলিম লীগ-বিএমএল",
    marka: "হাত (পাঞ্জা)",
    votes: "36542",
    countedCenter: "18",
    symbolImage: "https://i.ibb.co/nqLt6WBY/hand.png",
  },
  {
    id: 6,
    candidateName: "সৈয়দ শাহাদাৎ হোসেন",
    candidateImage: "https://i.ibb.co/8n2X2M7j/candidate7.jpg",
    partyName: "জাতীয় পাটি",
    marka: "লাঙ্গল",
    votes: "25478",
    countedCenter: "12",
    symbolImage: "https://i.ibb.co/8n2X2M7j/plough.png",
  },
];
